# Gradle Properties
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.parallel=true

# Project Details
project_jvm_version=25

project_group=net.izestudios.izemod
project_version=5.0.0
project_description=Minecraft Fabric utility mod designed to improve your gameplay.

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2

# Set to empty to use the Minecraft version above
supported_minecraft_versions=
